/**
 * IMCHAT_MUTATIONAA
 * 事件类型
 */
const IMCHAT_MUTATIONAA = 'IMCHAT_MUTATIONAA'

/**
 * IMCHAT_MUTATIONAA
 * 事件类型
 */
const IMCHAT_MUTATIONBB = 'IMCHAT_MUTATIONBB'

export default {
	IMCHAT_MUTATIONAA,
	IMCHAT_MUTATIONBB
}